#!/bin/bash

file=$1
host=$2
port=${3:-2021}
zephyr="http://${host}:${port}"
echo "curl -X POST -H "Content-Type: application/json" -d @${file} ${zephyr}/fabric/routes/add"
cat $file
curl -X POST -H "Content-Type: application/json" -d @${file} ${zephyr}/fabric/routes/add
